Fix double `nk:NT` header in ImportActivity which cause 402 response.
abrander/garmin-connect pull request #13
Opened 2021-06-11 05:33 UTC by leeeboo

Fix double `nk:NT` header in ImportActivity which cause 402 response.

2021-06-11 10:26 UTC, RobertWojtowicz commented
thank you very much, it works :)

2021-06-12 08:01 UTC, davidkroell commented
Works for me as well, thank you

2021-06-13 08:44 UTC, abrander requested changes
This is an awesome catch and an embarrassing mistake on my part :-)

Thanks for fixing this. I believe this can be merged as soon as the minor detail is fixed.

2021-06-13 08:44 UTC, abrander commented on Activity.go
> +	//req.Header.Add("nk", "NT")
Simply remove this line, history is preserved in git, if we ever need it again.

2021-06-23 20:10 UTC, abrander commented
Well, in the interest of moving forward, I'll merge this and fix it afterward. Thanks for your contribution, @leeeboo.

2021-06-23 20:10 UTC, merged